[package]
name = "pool1smartc-meta"
version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dev-dependencies]

[dependencies.pool1smartc]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.30.0"
